[meta]
name = "Chugmania Webhooks"
author = "DJ Balle"
category = "Utilities"
version = "1.0.1"

[game]
supported_games = ["Trackmania", "Turbo"]

[script]
timeout = 0
optional_dependencies = ["MLHook", "MLFeedRaceData", "VehicleState"]
