[meta]
name = "TM Webhooks"
author = "MrKallerud"
category = "Utilities"
version = "1.0.1"
siteid = 888

[game]
supported_games = ["Trackmania", "Turbo"]

[script]
timeout = 0
optional_dependencies = ["MLHook", "MLFeedRaceData", "VehicleState"]
